project:
  machine_name: newproject
  prefix: BLT
  human_name: 'New Project'
  profile:
    name: standard
  local:
    protocol: http
    hostname: '${project.machine_name}.docksal'
git:
  default_branch: master
  remotes: {  }
drush:
  aliases:
    remote: '${project.machine_name}.test'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
