project:
  machine_name: newproject
  prefix: BLT
  human_name: 'New Project'
  profile:
    name: standard
  local:
    protocol: http
    hostname: '${project.machine_name}.docksal'
git:
  default_branch: master
  remotes:
    - blaketestsync@svn-4140.devcloud.hosting.acquia.com:blaketestsync.git
drush:
  aliases:
    remote: 'blaketestsync.dev'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
phpunit:
  -
    config: ${docroot}/core/phpunit.xml.dist
    path: ${docroot}/modules/custom
